-- =====================================================================
-- PlaceNextAI - Sample Data
--
-- USER ACCOUNTS (admin, student, recruiter) are seeded automatically by
-- the application on first startup (see config/DataSeeder.java), because
-- passwords must be stored as BCrypt hashes generated by the app.
--
-- Auto-seeded login credentials:
--   Admin     : admin@placenextai.com   / Admin@123
--   Student   : ananya@college.edu      / Student@123
--   Recruiter : vikram@technova.com     / Recruit@123
--
-- The DataSeeder also inserts the 4 jobs below and 1 sample application.
-- Run this script ONLY if you want to add EXTRA jobs manually.
-- =====================================================================

USE placenextai_db;

INSERT INTO jobs (title, company, location, description, salary, skills_required, created_date)
VALUES
    ('DevOps Engineer', 'CloudSprint', 'Chennai, India',
     'Automate CI/CD pipelines, manage containerized deployments and monitor production infrastructure for our SaaS platform.',
     '8-11 LPA', 'Docker,Kubernetes,Jenkins,AWS,Linux', CURDATE()),
    ('Full Stack Developer', 'TechNova', 'Hyderabad, India',
     'Own features end to end across a React frontend and Spring Boot backend, from API design to polished UI.',
     '7-10 LPA', 'React,Java,Spring Boot,MySQL,REST APIs', CURDATE()),
    ('NLP Research Intern', 'NeuronLabs', 'Remote',
     'Experiment with sentence-transformer models for semantic resume-job matching and publish internal benchmarks.',
     '30k/month stipend', 'Python,NLP,Transformers,PyTorch', CURDATE());
