package com.placenextai.entity;

public enum EventType {
    LOGIN,
    PROFILE_UPDATED,
    RESUME_UPLOADED,
    APPLICATION_SUBMITTED,
    APPLICATION_STATUS_CHANGED,
    MOCK_INTERVIEW_COMPLETED,
    ROADMAP_ITEM_COMPLETED,
    FEEDBACK_RECEIVED,
    MENTOR_SESSION_BOOKED
}
